### ISSUE TITLE
Verification failed while extracting foundation-sites@^6.5.0

### ISSUE THREAD

**Issue by paxcodes** [laravel-frontend-presets/zurb-foundation#8]
To reproduce:

1. Created a fresh install of Laravel (5.7.19) via ``composer create-project`` inside a vagrant box with node v8.12.0 and npm v6.4.1
2. Followed instructions found in readme.md until I encountered the error at step 4: ``npm install``
 
Here's the stack trace:

```
16143 verbose stack Error: sha512-09gzfT9dHLoerYSMbs0ytgppn3YYw0h6Ug0q/RAYekzCUHQwJPUfNIXgX5iOBA8No2/zvfL5EeE6YrPBV90qxw== integrity checksum failed when using sha512: wanted sha512-09gzfT9dHLoerYSMbs0ytgppn3YYw0h6Ug0q/RAYekzCUHQwJPUfNIXgX5iOBA8No2/zvfL5EeE6YrPBV90qxw== but got sha512-+oD2qYMC+6cYcwUHih0E01xirbbHr6qPvRC32kKXbVeI/VsxU+5weQXxz+wNnR+xItfI9+DE3sB5f/MxmE3qow==. (11045609 bytes)
16143 verbose stack     at Transform.on (/usr/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
16143 verbose stack     at emitNone (events.js:111:20)
16143 verbose stack     at Transform.emit (events.js:208:7)
16143 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
16143 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
16143 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
16144 verbose cwd /home/vagrant/_code/laravel.vanilla
16145 verbose Linux 4.15.0-38-generic
16146 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
16147 verbose node v8.12.0
16148 verbose npm  v6.4.1
16149 error code EINTEGRITY
16150 error Verification failed while extracting foundation-sites@^6.5.0:
16150 error Verification failed while extracting foundation-sites@^6.5.0:
16150 error sha512-09gzfT9dHLoerYSMbs0ytgppn3YYw0h6Ug0q/RAYekzCUHQwJPUfNIXgX5iOBA8No2/zvfL5EeE6YrPBV90qxw== integrity checksum failed when using sha512: wanted sha512-09gzfT9dHLoerYSMbs0ytgppn3YYw0h6Ug0q/RAYekzCUHQwJPUfNIXgX5iOBA8No2/zvfL5EeE6YrPBV90qxw== but got sha512-+oD2qYMC+6cYcwUHih0E01xirbbHr6qPvRC32kKXbVeI/VsxU+5weQXxz+wNnR+xItfI9+DE3sB5f/MxmE3qow==. (11045609 bytes)
16151 verbose exit [ 1, true ]
```

I also tried running npm install in an existing laravel project and it gave the same error. It's what triggered me to see whether it would do the same with a fresh install.

**Comment by akosipax** [comment]
I just tried again and it seems to be working now.

**Comment by paxcodes** [comment]
I just tried again and it seems to be working now.
